[package]
name = "php-stacktrace"
version = "0.1.2"
authors = ["Oraoto <melegant2@gmail.com>"]

[dependencies]
elf = "0.0.10"
regex = "0.2.2"
gimli = "0.14.0"
byteorder = "1.1.0"
read-process-memory = "0.1.1"
libc = "0.2.32"
clap = "2.26.2"
serde = "1.0.15"
serde_derive = "1.0.15"
serde_json = "1.0.3"